language: node_js
node_js:
    - "node"
cache:
    yarn: true
script:
    - ( cd local_modules/contracts && yarn install )
    - export TESTRPC_PID=""
    - ( cd local_modules/contracts && yarn run testrpc & TESTRPC_PID=$! )
    - sleep 5
    - yarn test
    - kill -9 $TESTRPC_PID
env:
 - CXX=g++-4.8
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-4.8
